### ISSUE TITLE
Question: Will this work with @opentelemetry/instrumentation-http

### ISSUE THREAD

**Issue by ShravanSunder** [traceloop/openllmetry-js#103]
Hi,

I'm running otel from cloudflare workers using the various http libs and different exporters.  Will the instrumentation libs @traceloop/instrumentation-openai etc with @opentelemetry/instrumentation-http?

**Comment by nirga** [comment]
Yes @ShravanSunder, they will work :) 

Please use the discussions section in this repo or our [community slack](https://traceloop.com/slack) for such questions.
