### ISSUE TITLE
🚀 Feature: LlamaIndex Instrumentation

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry-js#22]
### Which component is this feature for?

All Packages

### 🔖 Feature description

Instrument [LlamaIndex](https://ts.llamaindex.ai/) apps, including adding attributes, similarly to our instrumentation in [Python](https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-llamaindex). The instrumentation should support all types of calls - streaming, non streaming, async, etc.

### 🎤 Why is this feature needed ?

Completness of OpenLLMetry-JS

### ✌️ How do you aim to achieve this?

Similarily to other instrumentations we have in this repo.

### 🔄️ Additional Information

This should instrument all typescript-equivalent APIs that we instrument in Python.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by Min2who** [comment]
can i get assigned?

**Comment by nirga** [comment]
@Kartik1397 is already taking this.
