### ISSUE TITLE
🚀 Feature: VertexAI Instrumentation

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry-js#31]
### Which component is this feature for?

All Packages

### 🔖 Feature description

Instrument calls to Google's [Vertex AI](https://cloud.google.com/nodejs/docs/reference/aiplatform/latest), including adding attributes for input parameters, model, etc. - similarly to our [OpenAI](https://github.com/traceloop/openllmetry-js/tree/main/packages/instrumentation-openai) instrumentation. The instrumentation should support all types of calls - streaming, non streaming, async, etc.

Instrumentation should support all models supported in our [Python instrumentation](https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-vertexai) including the new Gemini AI model.

This should specifically work with Google's new Gemini model.

### 🎤 Why is this feature needed ?

Completeness of OpenLLMetry

### ✌️ How do you aim to achieve this?

Similar to other instrumentations we have in this repo.

### 🔄️ Additional Information

* Make sure to initialize this in Traceloop SDK.
* Add proper tests.
* Add a sample in the sample app.
* Upload a screenshot from Traceloop with how your instrumentation works.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by Min2who** [comment]
/attempt #31

can i get assigned?

**Comment by 5war00p** [comment]
/attempt https://github.com/traceloop/openllmetry-js/issues/31
