### ISSUE TITLE
🚀 Feature: Pinecone Instrumentation

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry-js#32]
### Which component is this feature for?

All Packages

### 🔖 Feature description

Instrument calls to [Pinecone](https://github.com/pinecone-io/pinecone-ts-client), including adding attributes, similarly to our [Pinecone on Python](https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-pinecone) instrumentation. The instrumentation should support all types of calls - streaming, non streaming, async, etc.

### 🎤 Why is this feature needed?

Completeness of OpenLLMetry

### ✌️ How do you aim to achieve this?

Similar to other instrumentations, we have in this repo.

### 🔄️ Additional Information

* Make sure to initialize this in Traceloop SDK.
* Add proper tests.
* Add a sample in the sample app.
* Add a screenshot from Traceloop showing the instrumentation in action.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by ibishal** [comment]
/attempt #32
attempting this

**Comment by nirga** [comment]
@quest-bot stash 100

**Comment by kartikay-bagla** [comment]
@quest-bot embark

**Comment by kartikay-bagla** [comment]
@quest-bot embark

**Comment by nirga** [comment]
@quest-bot reward @kartikay-bagla
