### ISSUE TITLE
Bug: token count not being saved

### ISSUE THREAD

**Issue by kashifali11** [traceloop/openllmetry-js#352]
Token count is not being saved when a request is made to open ai.

**Comment by nirga** [comment]
Thanks for reporting @kashifali11! Can you provide some details as this [works for most cases](https://github.com/traceloop/openllmetry-js/blob/3b8224fac062b6da3f84311569a5ffcc2e3b8744/packages/instrumentation-openai/test/instrumentation.test.ts#L151). What API are you using?

**Comment by kashifali11** [comment]
I am using latest version of the sdk and openai version 4.11.1  
this is the span object that I get
{
  'gen_ai.system': 'OpenAI',
  'llm.request.type': 'chat',
  'gen_ai.request.model': 'gpt-3.5-turbo-1106',
  'gen_ai.request.max_tokens': 4096,
  'gen_ai.request.temperature': 0.7,
  'gen_ai.request.top_p': 1,
  'gen_ai.prompt.0.role': 'system',
  'gen_ai.prompt.0.content': '',
  'gen_ai.prompt.1.role': 'user',
  'gen_ai.prompt.1.content': 'Your name is naruto',
  'gen_ai.response.model': 'gpt-3.5-turbo-1106',
  'gen_ai.completion.0.finish_reason': 'stop',
  'gen_ai.completion.0.role': 'assistant',
  'gen_ai.completion.0.content': "I'm not Naruto, but I'm familiar with the character! Naruto is a popular anime and manga series about a young ninja with big dreams. If you have any questions about Naruto or anything else, feel free to ask!"
}
![image](https://github.com/traceloop/openllmetry-js/assets/81166580/0cbe6a01-6227-4488-a8df-7ef4f0116793)

**Comment by nirga** [comment]
Thanks @kashifali11! Any chance you're using the streaming API? Can you provide a small example of how you're calling OpenAI?

**Comment by kocobee** [comment]
Any update on this?

**Comment by nirga** [comment]
Sorry @kocobee this slipped between the cracks 🤦 
We're on it now. Can you provide a full snippet? This [code for example](https://github.com/traceloop/openllmetry/blob/d19c424ce94adbf69753db1db33c83182629d1d4/packages/sample-app/sample_app/methods_decorated_app.py#L28) provides token usage attributes.

**Comment by kashifali11** [comment]
Sorry for the confusion @nirga , I was using streaming api. Here is the code snippet
`
async function create_joke() {
  const responseStream = await traceloop.withTask({ name: "joke_creation" }, () => {
    return client.chat.completions.create({
      model: "gpt-3.5-turbo",
      messages: [{ role: "user", content: "Tell me a joke about opentelemetry" }],
      stream: true
    })
  });
  let result = "";
    for await (const chunk of responseStream) {
      result += chunk.choices[0]?.delta?.content || "";
    }
  return result;
}
`

**Comment by nirga** [comment]
Thanks @kashifali11! Fix is on the way!
