### ISSUE TITLE
Re-enable Pinecone tests

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry-js#57]
Following #56, we switched to mocked tests based on pre-recording of HTTP calls.
While this method worked well for OpenAI and other HTTP calls, I had some issues with the way our Pinecone tests are built.
This needs to be fixed and re-enabled.

**Comment by detunjiSamuel** [comment]
Hey,  I am new here. I would love to work on this issue.

**Comment by nirga** [comment]
Yes please! @detunjiSamuel :) 
You can look at other tests that we have for inspiration and I'm available on [slack](https://traceloop.com/slack)
