### ISSUE TITLE
Add OpenTelemetry Auto-Instrumentation for Langchain Library

### ISSUE THREAD

**Issue by galkleinman** [traceloop/openllmetry-js#7]
## Description

Add a new OpenTelemetry auto-instrumentation for Langchain Library. This instrumentation will greatly improve the observability and tracing capabilities of the Langchain based applications.

### Details

- Instrumentation Name: `instrumentation-langchain`
- Description: This instrumentation will provide automatic tracing and observability for the Langchain Library.
- Language: TypeScript

## Motivation

Adding this instrumentation will allow seamless integration of OpenTelemetry with Langchain enabling better visibility into chains which will be represented as `workflows`/`traces` in tracing data and Traceloop dashoard.

## High Level Instructions

1. Add a new package in this monorepo which should called `instrumentation-langchain`, with the same structure/boilerplate of `instrumentation-openai`.
2. Implement the auto instrumentation such that (quite similar to the instrumentation logic in the [python sdk](https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-langchain)):
- Every chain in Langchain will produce a span with  the name `<chain class name>.task` 
- [Traceloop Span Kind attribute](https://github.com/traceloop/openllmetry-js/blob/3fb61bfe543368e905b000cc7ce7522e1f445674/packages/ai-semantic-conventions/src/SemanticAttributes.ts#L39) from the `semantic-convetions` should be set to `task` and the span name is `<chain class name>.task`.
- Propagate also the Workflow Name and Correlation Ids as well.
- Produce workflow span For SequentialChain & RetrievalQA chains.
3. Integrate the above implemented instrumentation within `traceloop-sdk`
4. Add tests

## Checklist

Please make sure the following criteria are met:

- [x] I have searched the existing issues and confirmed that this request is not a duplicate.
- [x] I have provided a clear and concise description of the requested instrumentation.
- [x] I have explained the motivation and benefits of adding this instrumentation.
- [x] I have included any additional information or resources that may be relevant.

Thank you!

**Comment by mrkirthi-24** [comment]
hey @galkleinman What is the deadline for the submission??

**Comment by galkleinman** [comment]
@mrkirthi-24 we would like to

**Comment by galkleinman** [comment]
Thanks for attempting this one @mrkirthi-24, @aswathkk 💪 

We would like to have this one working next week, preferably before Tuesday 7/11.

Feel free to reach out (our community slack is the best channel for that) if you have any other questions.

**Comment by mrkirthi-24** [comment]
@galkleinman As a beginner, I gave it my best effort, but I would like to withdraw from this task as it is beyond my current level of expertise.

**Comment by wanghh2000** [comment]
Looks like opentelemetry can not recoginize langchain package.

**Comment by nirga** [comment]
@wanghh2000 WDYM, can you elaborate? (here or on slack)

**Comment by wanghh2000** [comment]
@nirga So far what I see from source code, Langchain 0.0.145 is the last version which export LLM chain from ./dist/index.js 
 and opentelemetry load packages defined in package.json. 
 It failed that I was trying to load `langchain/chains` in `Instrumentation`, seem opentelemetry can not see it. I'm still studying opentelemetry source code to check how to handle.

**Comment by nirga** [comment]
Thanks @wanghh2000! I've also started playing around with it in #15, and indeed there's an issue with instrumenting Langchain's inner packages.
I've [asked around in the CNCF slack](https://cloud-native.slack.com/archives/C01NL1GRPQR/p16995676915339390) but haven't gotten to try their suggestions yet (if you're not in the CNCF slack you can join [here](https://communityinviter.com/apps/cloud-native/cncf))

**Comment by wanghh2000** [comment]
Okay, I will take a look.

**Comment by nirga** [comment]
Fixed with #41
